// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoFy4tBLWRbrRNL8wUde3nrhN0MV8ybDo',
    appId: '1:341784388387:web:2cc8a0b6ad8f82f6302296',
    messagingSenderId: '341784388387',
    projectId: 'green-quest-fc8a6',
    authDomain: 'green-quest-fc8a6.firebaseapp.com',
    storageBucket: 'green-quest-fc8a6.appspot.com',
    measurementId: 'G-86B9SR1GJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzlqbsUjgQxjiZ-LEirB8mU7o3UKoMtCw',
    appId: '1:341784388387:android:e8ae133fd13a6ce1302296',
    messagingSenderId: '341784388387',
    projectId: 'green-quest-fc8a6',
    storageBucket: 'green-quest-fc8a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNagz8KC3AAdMabjxXuNsnWjBFWSvdOIs',
    appId: '1:341784388387:ios:52d830a71c3a9b46302296',
    messagingSenderId: '341784388387',
    projectId: 'green-quest-fc8a6',
    storageBucket: 'green-quest-fc8a6.appspot.com',
    iosBundleId: 'com.example.greenQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNagz8KC3AAdMabjxXuNsnWjBFWSvdOIs',
    appId: '1:341784388387:ios:233bd7e33a25fb69302296',
    messagingSenderId: '341784388387',
    projectId: 'green-quest-fc8a6',
    storageBucket: 'green-quest-fc8a6.appspot.com',
    iosBundleId: 'com.example.greenQuest.RunnerTests',
  );
}
